version: '3.9'

services:
    app:
        image: node:lts
        command: "bash -c 'npm i && npm run start'"
        volumes:
            - .:/usr/src/app:z
        working_dir: /usr/src/app
        ports:
            - '5173:5173'
