version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: "sh -c 'pnpm i && pnpm run --parallel start'"
        volumes:
            - .:/usr/src/app:z
        working_dir: /usr/src/app
        ports:
            - '5173:5173'
