version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile-dev
        command: "sh -c 'pnpm i && pnpm run --parallel dev'"
        volumes:
            - .:/usr/src/app:z
        working_dir: /usr/src/app
        ports:
            - '5173:5173'
            - '3000:3000'
        env_file: .env
        links:
            - redis

    redis:
        image: redis:latest
        ports:
            - '6379:6379'
        env_file: .env
        command: >
            --requirepass ${REDIS_PASSWORD}
